export const COMMISSIONS_COLUMNS: string[] = [
  'id',
  // 'appliance_id',
  'a.serial_number',
  'm.name',
  'creation_date',
  // 'problemDescription',
  'advice_given',
  'technician_id',
  'repair_date_id',
  // 'technicianReport',
  'client_visited',
  'commission_status',
  'client_id',
];
